name: Actions workflow

on:
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/6 * * * *"
  #push:
  pull_request:
    types: [closed, opened, reopened, assigned]
    
jobs:
  run-github-actions:
   runs-on: ubuntu-latest
   steps:
     - name: list files before
       run: >
         pwd
         ls -a
     - name: checkout
       uses: actions/checkout@v1
     - name: List files after
       run: >
         pwd
         ls -a
         echo $GITHUB_SHA
         echo $GITHUB_REPOSITORY
         echo "${{github.token}}"
     - name: simple js Actions
       id: greet
       uses: actions/hello-world-javascript-action@v1
       with:
         who-to-greet: Afnan
     - name: log greeting time
       run: echo "${{steps.greet.outputs.time}}"