name: node version setup

on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: log node version 
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: log node version 
        run: node -v

